### ISSUE TITLE
How to use an audio file in an asset catalog?

### ISSUE THREAD

**Issue by pukku** [delannoyk/AudioPlayer#10]
Hi! I was wondering if there was some way to use AudioPlayer to play an audio file located in an asset catalog? I'm brand new to iOS programming, so maybe I'm missing something, but it looks like the only way you can get at the items in an asset catalog (`NSDataAsset`) is via the `data` function, which gives you an`NSData` item; AudioPlayer requires an `NSURL`, and there doesn't seem to be a good way to pass the data.

Thanks,
Ricky

**Comment by delannoyk** [comment]
Hi!
Right now that's not supported so as a workaround, I would suggest storing your file in your app's bundle instead of in an asset catalog.
I don't have a lot of time this week to look into how to support it but that's definitely something I will do.

Can you let me know if the workaround I suggest works for your use-case?

Thanks,
Kevin

**Comment by pukku** [comment]
Hi! Putting the file in the bundle works just fine, so don't worry about it. I was more wondering if there was something that I was missing.

Thanks,
Ricky
