### ISSUE TITLE
After re-establishing the connection (after being offline) item is played from beginning and not resuming at current position

### ISSUE THREAD

**Issue by MattesGroeger** [delannoyk/AudioPlayer#43]
From my debugging it seems like it should theoretically work as you `seekToTime()` in the `retryOrPlayNext()` method. But in the `seekToTime` method it doesn't get any `seekableTimeRanges` back from the `AVPlayerItem` so it starts from the beginning. Any idea why this could be the case?

**Comment by delannoyk** [comment]
Yes, this is because the player is new and is re-buffering data in order to play, so the `currentProgression` is immediately set and is certainly not in the `seekableTimeRanges` yet.
Anyway, calling `player.seekToTime(...)` should fix this. I'm letting this open for you to confirm and eventually close if everything works out.

Thanks for reporting the issue.

**Comment by MattesGroeger** [comment]
Ok I guess you fixed it with 5b18414263fc4615274a068a5b5e77933e77b0f2

During my test it worked, at least most of the times. Great!
