### ISSUE TITLE
Update Xcode at testing server to 7.3.1

### ISSUE THREAD

**Issue by Samback** [delannoyk/AudioPlayer#60]
Currently you have Xcode 7.2 at Travic CI and that lead to the problems could you please to update it to the latest one.

**Comment by delannoyk** [comment]
Hi @Samback,
My current plan is to keep version < 1.0 in Swift 2.1 as I'd like it to be bug-fix only and to release Swift 2.2 with 1.0+.
Anyway, changing the setting in `.travis.yml` shouldn't change much except generate a few warnings on Selectors.
What issues are you currently having with Swift 2.1 (since it compiles just fine with Xcode 7.3.x)?

**Comment by Samback** [comment]
Hi @delannoyk 

I have update code to Swift 2.2 style, at least at one file.
Can we make an additional branch that would start to support new code style? Something like early-alpha-1.0.0? 
 Also I implement possibility to add headers if you need it on your request.
 Here is my issues after update:
https://travis-ci.org/delannoyk/AudioPlayer/builds/130569052

**Comment by delannoyk** [comment]
Hi Samback,

Yes but actually the main "features" on 1.0 are stabilisation, refactoring and unit tests. You can get a preview on the `feature/event_producers` branch.

Also, I'll take a look at your PR this week-end.
Thank you for your contributions :)

**Comment by delannoyk** [comment]
Closing this as master is now Swift 3.0 (no CocoaPods release yet though).
