### ISSUE TITLE
How does HLS quality switching work?

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#62]
I'd like to play a HLS audio only stream with three different audio quality settings. I discovered that AudioPlayer does have the possibility to switch between different streaming qualities. Does AudioPlayer really need to do that himself? Isn't this done by Apple's AVPlayer already?

**Comment by delannoyk** [comment]
The original app I developed this framework for is for a french radio station that has multiple icecast streams with different quality. They didn't (and still don't) support HLS streaming. Meaning I have ~4-5 URLs, if I remember correctly, for each stream quality. That's why I added the possibility to handle multiple quality based on multiple URLs.

**Comment by funkenstrahlen** [comment]
This means if I pass a HLS m3u8 to AudioPlayer as mediumQuality URL, it will pass this to AVPlayer and AVPlayer will manage the quality switching itself?

**Comment by delannoyk** [comment]
Yes, exactly.

**Comment by funkenstrahlen** [comment]
Ok great. Thank you for the quick reply. I think it is ok to keep the functionality in AudioPlayer for use cases like yours.
