### ISSUE TITLE
Functions of delegate should be marked as optional.

### ISSUE THREAD

**Issue by huynhphan89** [delannoyk/AudioPlayer#63]

**Comment by delannoyk** [comment]
Well, Swift protocols doesn't provide `optional func` out-of-the-box.
This would mean the `AudioPlayerDelegate` should be marked with `@objc`.

What I could do to make this happen, instead of working with an `@objc` protocol is to provide an extension to that protocol that implements methods that we should declare optional. What do you think?

**Comment by delannoyk** [comment]
Yup, pushed to `master`. No new release for now.
