### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by milanivarni** [delannoyk/AudioPlayer#91]
Hey @delannoyk,  I am trying to implement this library into Swift 3 Project but it shows errors:
![screen shot 2017-01-09 at 2 27 53 pm](https://cloud.githubusercontent.com/assets/22673922/21761273/da219e66-d677-11e6-9897-207dd8d4b00e.png)

Help would be appreciated.

**Comment by delannoyk** [comment]
Hey @milanivarni 
The swift 3 version is available. Can you run `pod update`?

**Comment by HamedPourjafar64** [comment]
it is not working even with pod update same issue here what should I do really stocked here

**Comment by dunqi** [comment]
You have to add the last commit-hash at the end in Cartfile.
".../AudioPlayer" "hash"

**Comment by almatri** [comment]
Same with me , not working with Swift 3 project

**Comment by dunqi** [comment]
The problem is, that you are not checking out the latest commit.

**Comment by almatri** [comment]
what about cocoapods?

**Comment by delannoyk** [comment]
> what about cocoapods?

`pod 'KDEAudioPlayer', :git => 'https://github.com/delannoyk/AudioPlayer', :branch => 'master'`
Sorry about that. It seems that CocoaPods doesn't like the fact that the 1.0 still contains 'beta' in the version. Will work on this project this week-end in order to get out of the beta. Shouldn't be much work, it's pretty solid already.
